package org.strasa.middleware.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import org.strasa.middleware.model.DbUser;
import org.strasa.middleware.model.DbUserExample.Criteria;
import org.strasa.middleware.model.DbUserExample.Criterion;
import org.strasa.middleware.model.DbUserExample;

public class DbUserSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String countByExample(DbUserExample example) {
		BEGIN();
		SELECT("count(*)");
		FROM("user");
		applyWhere(example, false);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String deleteByExample(DbUserExample example) {
		BEGIN();
		DELETE_FROM("user");
		applyWhere(example, false);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String insertSelective(DbUser record) {
		BEGIN();
		INSERT_INTO("user");
		if (record.getLastname() != null) {
			VALUES("lastname", "#{lastname,jdbcType=VARCHAR}");
		}
		if (record.getFirstname() != null) {
			VALUES("firstname", "#{firstname,jdbcType=VARCHAR}");
		}
		if (record.getMi() != null) {
			VALUES("mi", "#{mi,jdbcType=VARCHAR}");
		}
		if (record.getAgency() != null) {
			VALUES("agency", "#{agency,jdbcType=VARCHAR}");
		}
		if (record.getUsername() != null) {
			VALUES("username", "#{username,jdbcType=VARCHAR}");
		}
		if (record.getPassword() != null) {
			VALUES("password", "#{password,jdbcType=VARCHAR}");
		}
		if (record.getEmail() != null) {
			VALUES("email", "#{email,jdbcType=VARCHAR}");
		}
		if (record.getAddress() != null) {
			VALUES("address", "#{address,jdbcType=VARCHAR}");
		}
		if (record.getCountry() != null) {
			VALUES("country", "#{country,jdbcType=VARCHAR}");
		}
		if (record.getStatus() != null) {
			VALUES("status", "#{status,jdbcType=BIT}");
		}
		if (record.getRole() != null) {
			VALUES("role", "#{role,jdbcType=VARCHAR}");
		}
		if (record.getActive() != null) {
			VALUES("active", "#{active,jdbcType=BIT}");
		}
		if (record.getDateregistered() != null) {
			VALUES("dateregistered", "#{dateregistered,jdbcType=TIMESTAMP}");
		}
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String selectByExample(DbUserExample example) {
		BEGIN();
		if (example != null && example.isDistinct()) {
			SELECT_DISTINCT("id");
		} else {
			SELECT("id");
		}
		SELECT("lastname");
		SELECT("firstname");
		SELECT("mi");
		SELECT("agency");
		SELECT("username");
		SELECT("password");
		SELECT("email");
		SELECT("address");
		SELECT("country");
		SELECT("status");
		SELECT("role");
		SELECT("active");
		SELECT("dateregistered");
		FROM("user");
		applyWhere(example, false);
		if (example != null && example.getOrderByClause() != null) {
			ORDER_BY(example.getOrderByClause());
		}
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		DbUser record = (DbUser) parameter.get("record");
		DbUserExample example = (DbUserExample) parameter.get("example");
		BEGIN();
		UPDATE("user");
		if (record.getId() != null) {
			SET("id = #{record.id,jdbcType=INTEGER}");
		}
		if (record.getLastname() != null) {
			SET("lastname = #{record.lastname,jdbcType=VARCHAR}");
		}
		if (record.getFirstname() != null) {
			SET("firstname = #{record.firstname,jdbcType=VARCHAR}");
		}
		if (record.getMi() != null) {
			SET("mi = #{record.mi,jdbcType=VARCHAR}");
		}
		if (record.getAgency() != null) {
			SET("agency = #{record.agency,jdbcType=VARCHAR}");
		}
		if (record.getUsername() != null) {
			SET("username = #{record.username,jdbcType=VARCHAR}");
		}
		if (record.getPassword() != null) {
			SET("password = #{record.password,jdbcType=VARCHAR}");
		}
		if (record.getEmail() != null) {
			SET("email = #{record.email,jdbcType=VARCHAR}");
		}
		if (record.getAddress() != null) {
			SET("address = #{record.address,jdbcType=VARCHAR}");
		}
		if (record.getCountry() != null) {
			SET("country = #{record.country,jdbcType=VARCHAR}");
		}
		if (record.getStatus() != null) {
			SET("status = #{record.status,jdbcType=BIT}");
		}
		if (record.getRole() != null) {
			SET("role = #{record.role,jdbcType=VARCHAR}");
		}
		if (record.getActive() != null) {
			SET("active = #{record.active,jdbcType=BIT}");
		}
		if (record.getDateregistered() != null) {
			SET("dateregistered = #{record.dateregistered,jdbcType=TIMESTAMP}");
		}
		applyWhere(example, true);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String updateByExample(Map<String, Object> parameter) {
		BEGIN();
		UPDATE("user");
		SET("id = #{record.id,jdbcType=INTEGER}");
		SET("lastname = #{record.lastname,jdbcType=VARCHAR}");
		SET("firstname = #{record.firstname,jdbcType=VARCHAR}");
		SET("mi = #{record.mi,jdbcType=VARCHAR}");
		SET("agency = #{record.agency,jdbcType=VARCHAR}");
		SET("username = #{record.username,jdbcType=VARCHAR}");
		SET("password = #{record.password,jdbcType=VARCHAR}");
		SET("email = #{record.email,jdbcType=VARCHAR}");
		SET("address = #{record.address,jdbcType=VARCHAR}");
		SET("country = #{record.country,jdbcType=VARCHAR}");
		SET("status = #{record.status,jdbcType=BIT}");
		SET("role = #{record.role,jdbcType=VARCHAR}");
		SET("active = #{record.active,jdbcType=BIT}");
		SET("dateregistered = #{record.dateregistered,jdbcType=TIMESTAMP}");
		DbUserExample example = (DbUserExample) parameter.get("example");
		applyWhere(example, true);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String updateByPrimaryKeySelective(DbUser record) {
		BEGIN();
		UPDATE("user");
		if (record.getLastname() != null) {
			SET("lastname = #{lastname,jdbcType=VARCHAR}");
		}
		if (record.getFirstname() != null) {
			SET("firstname = #{firstname,jdbcType=VARCHAR}");
		}
		if (record.getMi() != null) {
			SET("mi = #{mi,jdbcType=VARCHAR}");
		}
		if (record.getAgency() != null) {
			SET("agency = #{agency,jdbcType=VARCHAR}");
		}
		if (record.getUsername() != null) {
			SET("username = #{username,jdbcType=VARCHAR}");
		}
		if (record.getPassword() != null) {
			SET("password = #{password,jdbcType=VARCHAR}");
		}
		if (record.getEmail() != null) {
			SET("email = #{email,jdbcType=VARCHAR}");
		}
		if (record.getAddress() != null) {
			SET("address = #{address,jdbcType=VARCHAR}");
		}
		if (record.getCountry() != null) {
			SET("country = #{country,jdbcType=VARCHAR}");
		}
		if (record.getStatus() != null) {
			SET("status = #{status,jdbcType=BIT}");
		}
		if (record.getRole() != null) {
			SET("role = #{role,jdbcType=VARCHAR}");
		}
		if (record.getActive() != null) {
			SET("active = #{active,jdbcType=BIT}");
		}
		if (record.getDateregistered() != null) {
			SET("dateregistered = #{dateregistered,jdbcType=TIMESTAMP}");
		}
		WHERE("id = #{id,jdbcType=INTEGER}");
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	protected void applyWhere(DbUserExample example,
			boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1,
									criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th,
									criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2,
									criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th,
									criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j,
										k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			WHERE(sb.toString());
		}
	}
}