package org.strasa.middleware.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.strasa.middleware.model.DesignStructure;
import org.strasa.middleware.model.DesignStructureExample;

public interface DesignStructureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designstructure
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @SelectProvider(type=DesignStructureSqlProvider.class, method="countByExample")
    int countByExample(DesignStructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designstructure
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @DeleteProvider(type=DesignStructureSqlProvider.class, method="deleteByExample")
    int deleteByExample(DesignStructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designstructure
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @Delete({
        "delete from designstructure",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designstructure
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @Insert({
        "insert into designstructure (design)",
        "values (#{design,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(DesignStructure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designstructure
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @InsertProvider(type=DesignStructureSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(DesignStructure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designstructure
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @SelectProvider(type=DesignStructureSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="design", property="design", jdbcType=JdbcType.VARCHAR)
    })
    List<DesignStructure> selectByExample(DesignStructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designstructure
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @Select({
        "select",
        "id, design",
        "from designstructure",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="design", property="design", jdbcType=JdbcType.VARCHAR)
    })
    DesignStructure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designstructure
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @UpdateProvider(type=DesignStructureSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") DesignStructure record, @Param("example") DesignStructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designstructure
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @UpdateProvider(type=DesignStructureSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") DesignStructure record, @Param("example") DesignStructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designstructure
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @UpdateProvider(type=DesignStructureSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(DesignStructure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designstructure
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @Update({
        "update designstructure",
        "set design = #{design,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(DesignStructure record);
}