package org.strasa.middleware.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.strasa.middleware.model.GermplasmSegment;
import org.strasa.middleware.model.GermplasmSegmentExample;

public interface GermplasmSegmentMapper {

	/**
     * This method was generated by MyBatis Generator. This method corresponds to the database table germplasm_segment
     * @mbggenerated  Thu Jun 26 14:16:41 PHT 2014
     */
    @SelectProvider(type = GermplasmSegmentSqlProvider.class, method = "countByExample")
    int countByExample(GermplasmSegmentExample example);

	/**
     * This method was generated by MyBatis Generator. This method corresponds to the database table germplasm_segment
     * @mbggenerated  Thu Jun 26 14:16:41 PHT 2014
     */
    @DeleteProvider(type = GermplasmSegmentSqlProvider.class, method = "deleteByExample")
    int deleteByExample(GermplasmSegmentExample example);

	/**
     * This method was generated by MyBatis Generator. This method corresponds to the database table germplasm_segment
     * @mbggenerated  Thu Jun 26 14:16:41 PHT 2014
     */
    @Delete(
    { "delete from germplasm_segment", "where id = #{id,jdbcType=INTEGER}" })
    int deleteByPrimaryKey(Integer id);

	/**
     * This method was generated by MyBatis Generator. This method corresponds to the database table germplasm_segment
     * @mbggenerated  Thu Jun 26 14:16:41 PHT 2014
     */
    @Insert(
    {
            "insert into germplasm_segment (germplasm_id, segment_id, ",
            "germplasm_segment_number, isHomogenous)",
            "values (#{germplasmId,jdbcType=INTEGER}, #{segmentId,jdbcType=INTEGER}, ",
            "#{germplasmSegmentNumber,jdbcType=INTEGER}, #{ishomogenous,jdbcType=CHAR})" })
    @Options(useGeneratedKeys = true, keyProperty = "id")
    int insert(GermplasmSegment record);

	/**
     * This method was generated by MyBatis Generator. This method corresponds to the database table germplasm_segment
     * @mbggenerated  Thu Jun 26 14:16:41 PHT 2014
     */
    @InsertProvider(type = GermplasmSegmentSqlProvider.class, method = "insertSelective")
    @Options(useGeneratedKeys = true, keyProperty = "id")
    int insertSelective(GermplasmSegment record);

	/**
     * This method was generated by MyBatis Generator. This method corresponds to the database table germplasm_segment
     * @mbggenerated  Thu Jun 26 14:16:41 PHT 2014
     */
    @SelectProvider(type = GermplasmSegmentSqlProvider.class, method = "selectByExample")
    @Results(
    {
            @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "germplasm_id", property = "germplasmId", jdbcType = JdbcType.INTEGER),
            @Result(column = "segment_id", property = "segmentId", jdbcType = JdbcType.INTEGER),
            @Result(column = "germplasm_segment_number", property = "germplasmSegmentNumber", jdbcType = JdbcType.INTEGER),
            @Result(column = "isHomogenous", property = "ishomogenous", jdbcType = JdbcType.CHAR) })
    List<GermplasmSegment> selectByExample(GermplasmSegmentExample example);

	/**
     * This method was generated by MyBatis Generator. This method corresponds to the database table germplasm_segment
     * @mbggenerated  Thu Jun 26 14:16:41 PHT 2014
     */
    @Select(
    {
            "select",
            "id, germplasm_id, segment_id, germplasm_segment_number, isHomogenous",
            "from germplasm_segment", "where id = #{id,jdbcType=INTEGER}" })
    @Results(
    {
            @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "germplasm_id", property = "germplasmId", jdbcType = JdbcType.INTEGER),
            @Result(column = "segment_id", property = "segmentId", jdbcType = JdbcType.INTEGER),
            @Result(column = "germplasm_segment_number", property = "germplasmSegmentNumber", jdbcType = JdbcType.INTEGER),
            @Result(column = "isHomogenous", property = "ishomogenous", jdbcType = JdbcType.CHAR) })
    GermplasmSegment selectByPrimaryKey(Integer id);

	/**
     * This method was generated by MyBatis Generator. This method corresponds to the database table germplasm_segment
     * @mbggenerated  Thu Jun 26 14:16:41 PHT 2014
     */
    @UpdateProvider(type = GermplasmSegmentSqlProvider.class, method = "updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GermplasmSegment record,
            @Param("example") GermplasmSegmentExample example);

	/**
     * This method was generated by MyBatis Generator. This method corresponds to the database table germplasm_segment
     * @mbggenerated  Thu Jun 26 14:16:41 PHT 2014
     */
    @UpdateProvider(type = GermplasmSegmentSqlProvider.class, method = "updateByExample")
    int updateByExample(@Param("record") GermplasmSegment record,
            @Param("example") GermplasmSegmentExample example);

	/**
     * This method was generated by MyBatis Generator. This method corresponds to the database table germplasm_segment
     * @mbggenerated  Thu Jun 26 14:16:41 PHT 2014
     */
    @UpdateProvider(type = GermplasmSegmentSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GermplasmSegment record);

	/**
     * This method was generated by MyBatis Generator. This method corresponds to the database table germplasm_segment
     * @mbggenerated  Thu Jun 26 14:16:41 PHT 2014
     */
    @Update(
    {
            "update germplasm_segment",
            "set germplasm_id = #{germplasmId,jdbcType=INTEGER},",
            "segment_id = #{segmentId,jdbcType=INTEGER},",
            "germplasm_segment_number = #{germplasmSegmentNumber,jdbcType=INTEGER},",
            "isHomogenous = #{ishomogenous,jdbcType=CHAR}",
            "where id = #{id,jdbcType=INTEGER}" })
    int updateByPrimaryKey(GermplasmSegment record);
}