package org.strasa.middleware.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;

import org.strasa.middleware.model.Location;
import org.strasa.middleware.model.LocationExample;
import org.strasa.middleware.model.LocationExample.Criteria;
import org.strasa.middleware.model.LocationExample.Criterion;

public class LocationSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table location
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String countByExample(LocationExample example) {
		BEGIN();
		SELECT("count(*)");
		FROM("location");
		applyWhere(example, false);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table location
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String deleteByExample(LocationExample example) {
		BEGIN();
		DELETE_FROM("location");
		applyWhere(example, false);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table location
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String insertSelective(Location record) {
		BEGIN();
		INSERT_INTO("location");
		if (record.getLocationname() != null) {
			VALUES("locationname", "#{locationname,jdbcType=VARCHAR}");
		}
		if (record.getCountry() != null) {
			VALUES("country", "#{country,jdbcType=VARCHAR}");
		}
		if (record.getProvince() != null) {
			VALUES("province", "#{province,jdbcType=VARCHAR}");
		}
		if (record.getRegion() != null) {
			VALUES("region", "#{region,jdbcType=VARCHAR}");
		}
		if (record.getAltitude() != null) {
			VALUES("altitude", "#{altitude,jdbcType=VARCHAR}");
		}
		if (record.getLatitude() != null) {
			VALUES("latitude", "#{latitude,jdbcType=VARCHAR}");
		}
		if (record.getWeatherstation() != null) {
			VALUES("weatherstation", "#{weatherstation,jdbcType=VARCHAR}");
		}
		if (record.getUserid() != null) {
			VALUES("userid", "#{userid,jdbcType=INTEGER}");
		}
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table location
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String selectByExample(LocationExample example) {
		BEGIN();
		if (example != null && example.isDistinct()) {
			SELECT_DISTINCT("id");
		} else {
			SELECT("id");
		}
		SELECT("locationname");
		SELECT("country");
		SELECT("province");
		SELECT("region");
		SELECT("altitude");
		SELECT("latitude");
		SELECT("weatherstation");
		SELECT("userid");
		FROM("location");
		applyWhere(example, false);
		if (example != null && example.getOrderByClause() != null) {
			ORDER_BY(example.getOrderByClause());
		}
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table location
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		Location record = (Location) parameter.get("record");
		LocationExample example = (LocationExample) parameter.get("example");
		BEGIN();
		UPDATE("location");
		if (record.getId() != null) {
			SET("id = #{record.id,jdbcType=INTEGER}");
		}
		if (record.getLocationname() != null) {
			SET("locationname = #{record.locationname,jdbcType=VARCHAR}");
		}
		if (record.getCountry() != null) {
			SET("country = #{record.country,jdbcType=VARCHAR}");
		}
		if (record.getProvince() != null) {
			SET("province = #{record.province,jdbcType=VARCHAR}");
		}
		if (record.getRegion() != null) {
			SET("region = #{record.region,jdbcType=VARCHAR}");
		}
		if (record.getAltitude() != null) {
			SET("altitude = #{record.altitude,jdbcType=VARCHAR}");
		}
		if (record.getLatitude() != null) {
			SET("latitude = #{record.latitude,jdbcType=VARCHAR}");
		}
		if (record.getWeatherstation() != null) {
			SET("weatherstation = #{record.weatherstation,jdbcType=VARCHAR}");
		}
		if (record.getUserid() != null) {
			SET("userid = #{record.userid,jdbcType=INTEGER}");
		}
		applyWhere(example, true);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table location
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String updateByExample(Map<String, Object> parameter) {
		BEGIN();
		UPDATE("location");
		SET("id = #{record.id,jdbcType=INTEGER}");
		SET("locationname = #{record.locationname,jdbcType=VARCHAR}");
		SET("country = #{record.country,jdbcType=VARCHAR}");
		SET("province = #{record.province,jdbcType=VARCHAR}");
		SET("region = #{record.region,jdbcType=VARCHAR}");
		SET("altitude = #{record.altitude,jdbcType=VARCHAR}");
		SET("latitude = #{record.latitude,jdbcType=VARCHAR}");
		SET("weatherstation = #{record.weatherstation,jdbcType=VARCHAR}");
		SET("userid = #{record.userid,jdbcType=INTEGER}");
		LocationExample example = (LocationExample) parameter.get("example");
		applyWhere(example, true);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table location
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String updateByPrimaryKeySelective(Location record) {
		BEGIN();
		UPDATE("location");
		if (record.getLocationname() != null) {
			SET("locationname = #{locationname,jdbcType=VARCHAR}");
		}
		if (record.getCountry() != null) {
			SET("country = #{country,jdbcType=VARCHAR}");
		}
		if (record.getProvince() != null) {
			SET("province = #{province,jdbcType=VARCHAR}");
		}
		if (record.getRegion() != null) {
			SET("region = #{region,jdbcType=VARCHAR}");
		}
		if (record.getAltitude() != null) {
			SET("altitude = #{altitude,jdbcType=VARCHAR}");
		}
		if (record.getLatitude() != null) {
			SET("latitude = #{latitude,jdbcType=VARCHAR}");
		}
		if (record.getWeatherstation() != null) {
			SET("weatherstation = #{weatherstation,jdbcType=VARCHAR}");
		}
		if (record.getUserid() != null) {
			SET("userid = #{userid,jdbcType=INTEGER}");
		}
		WHERE("id = #{id,jdbcType=INTEGER}");
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table location
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	protected void applyWhere(LocationExample example,
			boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1,
									criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th,
									criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2,
									criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th,
									criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j,
										k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			WHERE(sb.toString());
		}
	}
}