package org.strasa.middleware.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.strasa.middleware.model.SoilType;
import org.strasa.middleware.model.SoilTypeExample;

public interface SoilTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soiltype
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @SelectProvider(type=SoilTypeSqlProvider.class, method="countByExample")
    int countByExample(SoilTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soiltype
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @DeleteProvider(type=SoilTypeSqlProvider.class, method="deleteByExample")
    int deleteByExample(SoilTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soiltype
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @Delete({
        "delete from soiltype",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soiltype
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @Insert({
        "insert into soiltype (type)",
        "values (#{type,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(SoilType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soiltype
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @InsertProvider(type=SoilTypeSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(SoilType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soiltype
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @SelectProvider(type=SoilTypeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR)
    })
    List<SoilType> selectByExample(SoilTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soiltype
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @Select({
        "select",
        "id, type",
        "from soiltype",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR)
    })
    SoilType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soiltype
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @UpdateProvider(type=SoilTypeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SoilType record, @Param("example") SoilTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soiltype
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @UpdateProvider(type=SoilTypeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SoilType record, @Param("example") SoilTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soiltype
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @UpdateProvider(type=SoilTypeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SoilType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soiltype
     *
     * @mbggenerated Tue Feb 18 10:48:34 SGT 2014
     */
    @Update({
        "update soiltype",
        "set type = #{type,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SoilType record);
}