package org.strasa.middleware.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.strasa.middleware.model.StudyGermplasm;
import org.strasa.middleware.model.StudyGermplasmExample;

public interface StudyGermplasmMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studygermplasm
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@SelectProvider(type = StudyGermplasmSqlProvider.class, method = "countByExample")
	int countByExample(StudyGermplasmExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studygermplasm
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@DeleteProvider(type = StudyGermplasmSqlProvider.class, method = "deleteByExample")
	int deleteByExample(StudyGermplasmExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studygermplasm
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@Delete({ "delete from studygermplasm", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studygermplasm
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@Insert({ "insert into studygermplasm (gref, studyid, ",
			"dataset, userid)",
			"values (#{gref,jdbcType=INTEGER}, #{studyid,jdbcType=INTEGER}, ",
			"#{dataset,jdbcType=INTEGER}, #{userid,jdbcType=INTEGER})" })
	@Options(useGeneratedKeys = true, keyProperty = "id")
	int insert(StudyGermplasm record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studygermplasm
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@InsertProvider(type = StudyGermplasmSqlProvider.class, method = "insertSelective")
	@Options(useGeneratedKeys = true, keyProperty = "id")
	int insertSelective(StudyGermplasm record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studygermplasm
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@SelectProvider(type = StudyGermplasmSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "gref", property = "gref", jdbcType = JdbcType.INTEGER),
			@Result(column = "studyid", property = "studyid", jdbcType = JdbcType.INTEGER),
			@Result(column = "dataset", property = "dataset", jdbcType = JdbcType.INTEGER),
			@Result(column = "userid", property = "userid", jdbcType = JdbcType.INTEGER) })
	List<StudyGermplasm> selectByExample(StudyGermplasmExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studygermplasm
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@Select({ "select", "id, gref, studyid, dataset, userid",
			"from studygermplasm", "where id = #{id,jdbcType=INTEGER}" })
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "gref", property = "gref", jdbcType = JdbcType.INTEGER),
			@Result(column = "studyid", property = "studyid", jdbcType = JdbcType.INTEGER),
			@Result(column = "dataset", property = "dataset", jdbcType = JdbcType.INTEGER),
			@Result(column = "userid", property = "userid", jdbcType = JdbcType.INTEGER) })
	StudyGermplasm selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studygermplasm
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@UpdateProvider(type = StudyGermplasmSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") StudyGermplasm record,
			@Param("example") StudyGermplasmExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studygermplasm
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@UpdateProvider(type = StudyGermplasmSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") StudyGermplasm record,
			@Param("example") StudyGermplasmExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studygermplasm
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@UpdateProvider(type = StudyGermplasmSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(StudyGermplasm record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studygermplasm
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@Update({ "update studygermplasm", "set gref = #{gref,jdbcType=INTEGER},",
			"studyid = #{studyid,jdbcType=INTEGER},",
			"dataset = #{dataset,jdbcType=INTEGER},",
			"userid = #{userid,jdbcType=INTEGER}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(StudyGermplasm record);
}