package org.strasa.middleware.mapper;

import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.strasa.middleware.model.StudyRawDataByDataColumn;
import org.strasa.middleware.model.StudyRawDataByDataColumnExample;

public interface StudyRawDataByDataColumnMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyrawdata
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@SelectProvider(type = StudyRawDataByDataColumnSqlProvider.class, method = "countByExample")
	int countByExample(StudyRawDataByDataColumnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyrawdata
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@DeleteProvider(type = StudyRawDataByDataColumnSqlProvider.class, method = "deleteByExample")
	int deleteByExample(StudyRawDataByDataColumnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyrawdata
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@Insert({
			"insert into studyrawdata (studyid, dataset, ",
			"datacolumn, datavalue, ",
			"shared, userid)",
			"values (#{studyid,jdbcType=INTEGER}, #{dataset,jdbcType=INTEGER}, ",
			"#{datacolumn,jdbcType=VARCHAR}, #{datavalue,jdbcType=VARCHAR}, ",
			"#{shared,jdbcType=BIT}, #{userid,jdbcType=INTEGER})" })
	int insert(StudyRawDataByDataColumn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyrawdata
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@InsertProvider(type = StudyRawDataByDataColumnSqlProvider.class, method = "insertSelective")
	int insertSelective(StudyRawDataByDataColumn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyrawdata
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@SelectProvider(type = StudyRawDataByDataColumnSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "studyid", property = "studyid", jdbcType = JdbcType.INTEGER),
			@Result(column = "dataset", property = "dataset", jdbcType = JdbcType.INTEGER),
			@Result(column = "datacolumn", property = "datacolumn", jdbcType = JdbcType.VARCHAR),
			@Result(column = "datavalue", property = "datavalue", jdbcType = JdbcType.VARCHAR),
			@Result(column = "shared", property = "shared", jdbcType = JdbcType.BIT),
			@Result(column = "userid", property = "userid", jdbcType = JdbcType.INTEGER) })
	List<StudyRawDataByDataColumn> selectByExample(
			StudyRawDataByDataColumnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyrawdata
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@UpdateProvider(type = StudyRawDataByDataColumnSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(
			@Param("record") StudyRawDataByDataColumn record,
			@Param("example") StudyRawDataByDataColumnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyrawdata
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@UpdateProvider(type = StudyRawDataByDataColumnSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") StudyRawDataByDataColumn record,
			@Param("example") StudyRawDataByDataColumnExample example);
}