package org.strasa.middleware.mapper;

import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.strasa.middleware.model.StudyRawDataByDataColumn;
import org.strasa.middleware.model.StudyRawDataByDataColumnExample;

public interface StudyRawDerivedDataByDataColumnMapper extends StudyRawDataByDataColumnMapper{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyderiveddata
	 * @mbggenerated  Thu Oct 31 10:09:05 SGT 2013
	 */
	@SelectProvider(type = StudyRawDerivedDataByDataColumnSqlProvider.class, method = "countByExample")
	int countByExample(StudyRawDataByDataColumnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyderiveddata
	 * @mbggenerated  Thu Oct 31 10:09:05 SGT 2013
	 */
	@DeleteProvider(type = StudyRawDerivedDataByDataColumnSqlProvider.class, method = "deleteByExample")
	int deleteByExample(StudyRawDataByDataColumnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyderiveddata
	 * @mbggenerated  Thu Oct 31 10:09:05 SGT 2013
	 */
	@Insert({
			"insert into studyderiveddata (studyid, datacolumn, ",
			"datavalue)",
			"values (#{studyid,jdbcType=INTEGER}, #{datacolumn,jdbcType=VARCHAR}, ",
			"#{datavalue,jdbcType=VARCHAR})" })
	int insert(StudyRawDataByDataColumn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyderiveddata
	 * @mbggenerated  Thu Oct 31 10:09:05 SGT 2013
	 */
	@InsertProvider(type = StudyRawDerivedDataByDataColumnSqlProvider.class, method = "insertSelective")
	int insertSelective(StudyRawDataByDataColumn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyderiveddata
	 * @mbggenerated  Thu Oct 31 10:09:05 SGT 2013
	 */
	@SelectProvider(type = StudyRawDerivedDataByDataColumnSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "studyid", property = "studyid", jdbcType = JdbcType.INTEGER),
			@Result(column = "datacolumn", property = "datacolumn", jdbcType = JdbcType.VARCHAR),
			@Result(column = "datavalue", property = "datavalue", jdbcType = JdbcType.VARCHAR) })
	List<StudyRawDataByDataColumn> selectByExample(
			StudyRawDataByDataColumnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyderiveddata
	 * @mbggenerated  Thu Oct 31 10:09:05 SGT 2013
	 */
	@UpdateProvider(type = StudyRawDerivedDataByDataColumnSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(
			@Param("record") StudyRawDataByDataColumn record,
			@Param("example") StudyRawDataByDataColumnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyderiveddata
	 * @mbggenerated  Thu Oct 31 10:09:05 SGT 2013
	 */
	@UpdateProvider(type = StudyRawDerivedDataByDataColumnSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") StudyRawDataByDataColumn record,
			@Param("example") StudyRawDataByDataColumnExample example);
}