package org.strasa.middleware.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.strasa.middleware.model.StudyLocation;
import org.strasa.middleware.model.StudyLocationExample;

public interface StudyLocationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studylocation
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@SelectProvider(type = StudyLocationSqlProvider.class, method = "countByExample")
	int countByExample(StudyLocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studylocation
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@DeleteProvider(type = StudyLocationSqlProvider.class, method = "deleteByExample")
	int deleteByExample(StudyLocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studylocation
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@Delete({ "delete from studylocation", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studylocation
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@Insert({
			"insert into studylocation (studyid, dataset, ",
			"locationid)",
			"values (#{studyid,jdbcType=INTEGER}, #{dataset,jdbcType=INTEGER}, ",
			"#{locationid,jdbcType=INTEGER})" })
	@Options(useGeneratedKeys = true, keyProperty = "id")
	int insert(StudyLocation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studylocation
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@InsertProvider(type = StudyLocationSqlProvider.class, method = "insertSelective")
	@Options(useGeneratedKeys = true, keyProperty = "id")
	int insertSelective(StudyLocation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studylocation
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@SelectProvider(type = StudyLocationSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "studyid", property = "studyid", jdbcType = JdbcType.INTEGER),
			@Result(column = "dataset", property = "dataset", jdbcType = JdbcType.INTEGER),
			@Result(column = "locationid", property = "locationid", jdbcType = JdbcType.INTEGER) })
	List<StudyLocation> selectByExample(StudyLocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studylocation
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@Select({ "select", "id, studyid, dataset, locationid",
			"from studylocation", "where id = #{id,jdbcType=INTEGER}" })
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "studyid", property = "studyid", jdbcType = JdbcType.INTEGER),
			@Result(column = "dataset", property = "dataset", jdbcType = JdbcType.INTEGER),
			@Result(column = "locationid", property = "locationid", jdbcType = JdbcType.INTEGER) })
	StudyLocation selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studylocation
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@UpdateProvider(type = StudyLocationSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") StudyLocation record,
			@Param("example") StudyLocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studylocation
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@UpdateProvider(type = StudyLocationSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") StudyLocation record,
			@Param("example") StudyLocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studylocation
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@UpdateProvider(type = StudyLocationSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(StudyLocation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studylocation
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@Update({ "update studylocation",
			"set studyid = #{studyid,jdbcType=INTEGER},",
			"dataset = #{dataset,jdbcType=INTEGER},",
			"locationid = #{locationid,jdbcType=INTEGER}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(StudyLocation record);
}