package org.strasa.middleware.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.strasa.middleware.model.StudyAgronomy;
import org.strasa.middleware.model.StudyAgronomyExample;

public interface StudyAgronomyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyagronomy
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@SelectProvider(type = StudyAgronomySqlProvider.class, method = "countByExample")
	int countByExample(StudyAgronomyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyagronomy
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@DeleteProvider(type = StudyAgronomySqlProvider.class, method = "deleteByExample")
	int deleteByExample(StudyAgronomyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyagronomy
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@Delete({ "delete from studyagronomy", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyagronomy
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@Insert({
			"insert into studyagronomy (studysiteid, plantingtypeid, ",
			"sowingdate, harvestdate, ",
			"fertilization, density)",
			"values (#{studysiteid,jdbcType=INTEGER}, #{plantingtypeid,jdbcType=INTEGER}, ",
			"#{sowingdate,jdbcType=DATE}, #{harvestdate,jdbcType=DATE}, ",
			"#{fertilization,jdbcType=VARCHAR}, #{density,jdbcType=VARCHAR})" })
	@Options(useGeneratedKeys = true, keyProperty = "id")
	int insert(StudyAgronomy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyagronomy
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@InsertProvider(type = StudyAgronomySqlProvider.class, method = "insertSelective")
	@Options(useGeneratedKeys = true, keyProperty = "id")
	int insertSelective(StudyAgronomy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyagronomy
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@SelectProvider(type = StudyAgronomySqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "studysiteid", property = "studysiteid", jdbcType = JdbcType.INTEGER),
			@Result(column = "plantingtypeid", property = "plantingtypeid", jdbcType = JdbcType.INTEGER),
			@Result(column = "sowingdate", property = "sowingdate", jdbcType = JdbcType.DATE),
			@Result(column = "harvestdate", property = "harvestdate", jdbcType = JdbcType.DATE),
			@Result(column = "fertilization", property = "fertilization", jdbcType = JdbcType.VARCHAR),
			@Result(column = "density", property = "density", jdbcType = JdbcType.VARCHAR) })
	List<StudyAgronomy> selectByExample(StudyAgronomyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyagronomy
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@Select({
			"select",
			"id, studysiteid, plantingtypeid, sowingdate, harvestdate, fertilization, density",
			"from studyagronomy", "where id = #{id,jdbcType=INTEGER}" })
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "studysiteid", property = "studysiteid", jdbcType = JdbcType.INTEGER),
			@Result(column = "plantingtypeid", property = "plantingtypeid", jdbcType = JdbcType.INTEGER),
			@Result(column = "sowingdate", property = "sowingdate", jdbcType = JdbcType.DATE),
			@Result(column = "harvestdate", property = "harvestdate", jdbcType = JdbcType.DATE),
			@Result(column = "fertilization", property = "fertilization", jdbcType = JdbcType.VARCHAR),
			@Result(column = "density", property = "density", jdbcType = JdbcType.VARCHAR) })
	StudyAgronomy selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyagronomy
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@UpdateProvider(type = StudyAgronomySqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") StudyAgronomy record,
			@Param("example") StudyAgronomyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyagronomy
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@UpdateProvider(type = StudyAgronomySqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") StudyAgronomy record,
			@Param("example") StudyAgronomyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyagronomy
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@UpdateProvider(type = StudyAgronomySqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(StudyAgronomy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyagronomy
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	@Update({ "update studyagronomy",
			"set studysiteid = #{studysiteid,jdbcType=INTEGER},",
			"plantingtypeid = #{plantingtypeid,jdbcType=INTEGER},",
			"sowingdate = #{sowingdate,jdbcType=DATE},",
			"harvestdate = #{harvestdate,jdbcType=DATE},",
			"fertilization = #{fertilization,jdbcType=VARCHAR},",
			"density = #{density,jdbcType=VARCHAR}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(StudyAgronomy record);
}