package org.strasa.middleware.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.strasa.middleware.model.UserDataFile;
import org.strasa.middleware.model.UserDataFileExample;

public interface UserDataFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdatafile
     *
     * @mbggenerated Sat Nov 02 19:41:12 PHT 2013
     */
    @SelectProvider(type=UserDataFileSqlProvider.class, method="countByExample")
    int countByExample(UserDataFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdatafile
     *
     * @mbggenerated Sat Nov 02 19:41:12 PHT 2013
     */
    @DeleteProvider(type=UserDataFileSqlProvider.class, method="deleteByExample")
    int deleteByExample(UserDataFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdatafile
     *
     * @mbggenerated Sat Nov 02 19:41:12 PHT 2013
     */
    @Delete({
        "delete from userdatafile",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdatafile
     *
     * @mbggenerated Sat Nov 02 19:41:12 PHT 2013
     */
    @Insert({
        "insert into userdatafile (userid, studyid, ",
        "filename, filetype, ",
        "userfilecol, filepath, ",
        "flag)",
        "values (#{userid,jdbcType=INTEGER}, #{studyid,jdbcType=INTEGER}, ",
        "#{filename,jdbcType=VARCHAR}, #{filetype,jdbcType=VARCHAR}, ",
        "#{userfilecol,jdbcType=VARCHAR}, #{filepath,jdbcType=VARCHAR}, ",
        "#{flag,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(UserDataFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdatafile
     *
     * @mbggenerated Sat Nov 02 19:41:12 PHT 2013
     */
    @InsertProvider(type=UserDataFileSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(UserDataFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdatafile
     *
     * @mbggenerated Sat Nov 02 19:41:12 PHT 2013
     */
    @SelectProvider(type=UserDataFileSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="userid", property="userid", jdbcType=JdbcType.INTEGER),
        @Result(column="studyid", property="studyid", jdbcType=JdbcType.INTEGER),
        @Result(column="filename", property="filename", jdbcType=JdbcType.VARCHAR),
        @Result(column="filetype", property="filetype", jdbcType=JdbcType.VARCHAR),
        @Result(column="userfilecol", property="userfilecol", jdbcType=JdbcType.VARCHAR),
        @Result(column="filepath", property="filepath", jdbcType=JdbcType.VARCHAR),
        @Result(column="flag", property="flag", jdbcType=JdbcType.VARCHAR)
    })
    List<UserDataFile> selectByExample(UserDataFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdatafile
     *
     * @mbggenerated Sat Nov 02 19:41:12 PHT 2013
     */
    @Select({
        "select",
        "id, userid, studyid, filename, filetype, userfilecol, filepath, flag",
        "from userdatafile",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="userid", property="userid", jdbcType=JdbcType.INTEGER),
        @Result(column="studyid", property="studyid", jdbcType=JdbcType.INTEGER),
        @Result(column="filename", property="filename", jdbcType=JdbcType.VARCHAR),
        @Result(column="filetype", property="filetype", jdbcType=JdbcType.VARCHAR),
        @Result(column="userfilecol", property="userfilecol", jdbcType=JdbcType.VARCHAR),
        @Result(column="filepath", property="filepath", jdbcType=JdbcType.VARCHAR),
        @Result(column="flag", property="flag", jdbcType=JdbcType.VARCHAR)
    })
    UserDataFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdatafile
     *
     * @mbggenerated Sat Nov 02 19:41:12 PHT 2013
     */
    @UpdateProvider(type=UserDataFileSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UserDataFile record, @Param("example") UserDataFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdatafile
     *
     * @mbggenerated Sat Nov 02 19:41:12 PHT 2013
     */
    @UpdateProvider(type=UserDataFileSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") UserDataFile record, @Param("example") UserDataFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdatafile
     *
     * @mbggenerated Sat Nov 02 19:41:12 PHT 2013
     */
    @UpdateProvider(type=UserDataFileSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserDataFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdatafile
     *
     * @mbggenerated Sat Nov 02 19:41:12 PHT 2013
     */
    @Update({
        "update userdatafile",
        "set userid = #{userid,jdbcType=INTEGER},",
          "studyid = #{studyid,jdbcType=INTEGER},",
          "filename = #{filename,jdbcType=VARCHAR},",
          "filetype = #{filetype,jdbcType=VARCHAR},",
          "userfilecol = #{userfilecol,jdbcType=VARCHAR},",
          "filepath = #{filepath,jdbcType=VARCHAR},",
          "flag = #{flag,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserDataFile record);
}