package org.strasa.middleware.model;

public class Country {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column country.cntryid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer cntryid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column country.isonum
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer isonum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column country.isotwo
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String isotwo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column country.isothree
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String isothree;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column country.faothree
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String faothree;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column country.fips
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String fips;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column country.wb
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String wb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column country.isofull
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String isofull;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column country.isoabbr
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String isoabbr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column country.cont
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String cont;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column country.scntry
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer scntry;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column country.ecntry
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer ecntry;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column country.cchange
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer cchange;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column country.cntryid
	 * @return  the value of country.cntryid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getCntryid() {
		return cntryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column country.cntryid
	 * @param cntryid  the value for country.cntryid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setCntryid(Integer cntryid) {
		this.cntryid = cntryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column country.isonum
	 * @return  the value of country.isonum
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getIsonum() {
		return isonum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column country.isonum
	 * @param isonum  the value for country.isonum
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setIsonum(Integer isonum) {
		this.isonum = isonum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column country.isotwo
	 * @return  the value of country.isotwo
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getIsotwo() {
		return isotwo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column country.isotwo
	 * @param isotwo  the value for country.isotwo
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setIsotwo(String isotwo) {
		this.isotwo = isotwo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column country.isothree
	 * @return  the value of country.isothree
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getIsothree() {
		return isothree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column country.isothree
	 * @param isothree  the value for country.isothree
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setIsothree(String isothree) {
		this.isothree = isothree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column country.faothree
	 * @return  the value of country.faothree
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getFaothree() {
		return faothree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column country.faothree
	 * @param faothree  the value for country.faothree
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setFaothree(String faothree) {
		this.faothree = faothree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column country.fips
	 * @return  the value of country.fips
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getFips() {
		return fips;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column country.fips
	 * @param fips  the value for country.fips
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setFips(String fips) {
		this.fips = fips;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column country.wb
	 * @return  the value of country.wb
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getWb() {
		return wb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column country.wb
	 * @param wb  the value for country.wb
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setWb(String wb) {
		this.wb = wb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column country.isofull
	 * @return  the value of country.isofull
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getIsofull() {
		return isofull;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column country.isofull
	 * @param isofull  the value for country.isofull
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setIsofull(String isofull) {
		this.isofull = isofull;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column country.isoabbr
	 * @return  the value of country.isoabbr
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getIsoabbr() {
		return isoabbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column country.isoabbr
	 * @param isoabbr  the value for country.isoabbr
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setIsoabbr(String isoabbr) {
		this.isoabbr = isoabbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column country.cont
	 * @return  the value of country.cont
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getCont() {
		return cont;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column country.cont
	 * @param cont  the value for country.cont
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setCont(String cont) {
		this.cont = cont;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column country.scntry
	 * @return  the value of country.scntry
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getScntry() {
		return scntry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column country.scntry
	 * @param scntry  the value for country.scntry
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setScntry(Integer scntry) {
		this.scntry = scntry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column country.ecntry
	 * @return  the value of country.ecntry
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getEcntry() {
		return ecntry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column country.ecntry
	 * @param ecntry  the value for country.ecntry
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setEcntry(Integer ecntry) {
		this.ecntry = ecntry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column country.cchange
	 * @return  the value of country.cchange
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getCchange() {
		return cchange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column country.cchange
	 * @param cchange  the value for country.cchange
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setCchange(Integer cchange) {
		this.cchange = cchange;
	}
}