package org.strasa.middleware.model;

public class DistributionAndExtension {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column distributionandextension.id
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column distributionandextension.programid
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	private Integer programid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column distributionandextension.projectid
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	private Integer projectid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column distributionandextension.germplasmname
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	private String germplasmname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column distributionandextension.yearextension
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	private String yearextension;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column distributionandextension.locationextension
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	private String locationextension;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column distributionandextension.countryextension
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	private String countryextension;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column distributionandextension.plantingarea
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	private Double plantingarea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column distributionandextension.datasource
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	private String datasource;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column distributionandextension.seedavailability
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	private Integer seedavailability;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column distributionandextension.amountseeddistributed
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	private Integer amountseeddistributed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column distributionandextension.numfarmersadopted
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	private Integer numfarmersadopted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column distributionandextension.amountseedsproduced
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	private Double amountseedsproduced;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column distributionandextension.userid
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	private Integer userid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column distributionandextension.id
	 * @return  the value of distributionandextension.id
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column distributionandextension.id
	 * @param id  the value for distributionandextension.id
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column distributionandextension.programid
	 * @return  the value of distributionandextension.programid
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public Integer getProgramid() {
		return programid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column distributionandextension.programid
	 * @param programid  the value for distributionandextension.programid
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public void setProgramid(Integer programid) {
		this.programid = programid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column distributionandextension.projectid
	 * @return  the value of distributionandextension.projectid
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public Integer getProjectid() {
		return projectid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column distributionandextension.projectid
	 * @param projectid  the value for distributionandextension.projectid
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public void setProjectid(Integer projectid) {
		this.projectid = projectid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column distributionandextension.germplasmname
	 * @return  the value of distributionandextension.germplasmname
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public String getGermplasmname() {
		return germplasmname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column distributionandextension.germplasmname
	 * @param germplasmname  the value for distributionandextension.germplasmname
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public void setGermplasmname(String germplasmname) {
		this.germplasmname = germplasmname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column distributionandextension.yearextension
	 * @return  the value of distributionandextension.yearextension
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public String getYearextension() {
		return yearextension;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column distributionandextension.yearextension
	 * @param yearextension  the value for distributionandextension.yearextension
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public void setYearextension(String yearextension) {
		this.yearextension = yearextension;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column distributionandextension.locationextension
	 * @return  the value of distributionandextension.locationextension
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public String getLocationextension() {
		return locationextension;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column distributionandextension.locationextension
	 * @param locationextension  the value for distributionandextension.locationextension
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public void setLocationextension(String locationextension) {
		this.locationextension = locationextension;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column distributionandextension.countryextension
	 * @return  the value of distributionandextension.countryextension
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public String getCountryextension() {
		return countryextension;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column distributionandextension.countryextension
	 * @param countryextension  the value for distributionandextension.countryextension
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public void setCountryextension(String countryextension) {
		this.countryextension = countryextension;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column distributionandextension.plantingarea
	 * @return  the value of distributionandextension.plantingarea
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public Double getPlantingarea() {
		return plantingarea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column distributionandextension.plantingarea
	 * @param plantingarea  the value for distributionandextension.plantingarea
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public void setPlantingarea(Double plantingarea) {
		this.plantingarea = plantingarea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column distributionandextension.datasource
	 * @return  the value of distributionandextension.datasource
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public String getDatasource() {
		return datasource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column distributionandextension.datasource
	 * @param datasource  the value for distributionandextension.datasource
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public void setDatasource(String datasource) {
		this.datasource = datasource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column distributionandextension.seedavailability
	 * @return  the value of distributionandextension.seedavailability
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public Integer getSeedavailability() {
		return seedavailability;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column distributionandextension.seedavailability
	 * @param seedavailability  the value for distributionandextension.seedavailability
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public void setSeedavailability(Integer seedavailability) {
		this.seedavailability = seedavailability;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column distributionandextension.amountseeddistributed
	 * @return  the value of distributionandextension.amountseeddistributed
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public Integer getAmountseeddistributed() {
		return amountseeddistributed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column distributionandextension.amountseeddistributed
	 * @param amountseeddistributed  the value for distributionandextension.amountseeddistributed
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public void setAmountseeddistributed(Integer amountseeddistributed) {
		this.amountseeddistributed = amountseeddistributed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column distributionandextension.numfarmersadopted
	 * @return  the value of distributionandextension.numfarmersadopted
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public Integer getNumfarmersadopted() {
		return numfarmersadopted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column distributionandextension.numfarmersadopted
	 * @param numfarmersadopted  the value for distributionandextension.numfarmersadopted
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public void setNumfarmersadopted(Integer numfarmersadopted) {
		this.numfarmersadopted = numfarmersadopted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column distributionandextension.amountseedsproduced
	 * @return  the value of distributionandextension.amountseedsproduced
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public Double getAmountseedsproduced() {
		return amountseedsproduced;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column distributionandextension.amountseedsproduced
	 * @param amountseedsproduced  the value for distributionandextension.amountseedsproduced
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public void setAmountseedsproduced(Double amountseedsproduced) {
		this.amountseedsproduced = amountseedsproduced;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column distributionandextension.userid
	 * @return  the value of distributionandextension.userid
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column distributionandextension.userid
	 * @param userid  the value for distributionandextension.userid
	 * @mbggenerated  Wed Mar 12 09:07:47 SGT 2014
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}
}