package org.strasa.middleware.model;

public class Germplasm {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.gid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer gid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.germplasmname
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String germplasmname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.othername
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String othername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.breeder
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String breeder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.germplasmtypeid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer germplasmtypeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.irnumber
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String irnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.ircross
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String ircross;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.parentage
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String parentage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.femaleparent
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String femaleparent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.maleparent
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String maleparent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.selectionhistory
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String selectionhistory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.source
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String source;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.remarks
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.userid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer userid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.id
	 * @return  the value of germplasm.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.id
	 * @param id  the value for germplasm.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.gid
	 * @return  the value of germplasm.gid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getGid() {
		return gid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.gid
	 * @param gid  the value for germplasm.gid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setGid(Integer gid) {
		this.gid = gid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.germplasmname
	 * @return  the value of germplasm.germplasmname
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getGermplasmname() {
		return germplasmname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.germplasmname
	 * @param germplasmname  the value for germplasm.germplasmname
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setGermplasmname(String germplasmname) {
		this.germplasmname = germplasmname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.othername
	 * @return  the value of germplasm.othername
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getOthername() {
		return othername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.othername
	 * @param othername  the value for germplasm.othername
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setOthername(String othername) {
		this.othername = othername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.breeder
	 * @return  the value of germplasm.breeder
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getBreeder() {
		return breeder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.breeder
	 * @param breeder  the value for germplasm.breeder
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setBreeder(String breeder) {
		this.breeder = breeder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.germplasmtypeid
	 * @return  the value of germplasm.germplasmtypeid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getGermplasmtypeid() {
		return germplasmtypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.germplasmtypeid
	 * @param germplasmtypeid  the value for germplasm.germplasmtypeid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setGermplasmtypeid(Integer germplasmtypeid) {
		this.germplasmtypeid = germplasmtypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.irnumber
	 * @return  the value of germplasm.irnumber
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getIrnumber() {
		return irnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.irnumber
	 * @param irnumber  the value for germplasm.irnumber
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setIrnumber(String irnumber) {
		this.irnumber = irnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.ircross
	 * @return  the value of germplasm.ircross
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getIrcross() {
		return ircross;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.ircross
	 * @param ircross  the value for germplasm.ircross
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setIrcross(String ircross) {
		this.ircross = ircross;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.parentage
	 * @return  the value of germplasm.parentage
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getParentage() {
		return parentage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.parentage
	 * @param parentage  the value for germplasm.parentage
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setParentage(String parentage) {
		this.parentage = parentage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.femaleparent
	 * @return  the value of germplasm.femaleparent
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getFemaleparent() {
		return femaleparent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.femaleparent
	 * @param femaleparent  the value for germplasm.femaleparent
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setFemaleparent(String femaleparent) {
		this.femaleparent = femaleparent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.maleparent
	 * @return  the value of germplasm.maleparent
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getMaleparent() {
		return maleparent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.maleparent
	 * @param maleparent  the value for germplasm.maleparent
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setMaleparent(String maleparent) {
		this.maleparent = maleparent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.selectionhistory
	 * @return  the value of germplasm.selectionhistory
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getSelectionhistory() {
		return selectionhistory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.selectionhistory
	 * @param selectionhistory  the value for germplasm.selectionhistory
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setSelectionhistory(String selectionhistory) {
		this.selectionhistory = selectionhistory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.source
	 * @return  the value of germplasm.source
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getSource() {
		return source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.source
	 * @param source  the value for germplasm.source
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setSource(String source) {
		this.source = source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.remarks
	 * @return  the value of germplasm.remarks
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.remarks
	 * @param remarks  the value for germplasm.remarks
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.userid
	 * @return  the value of germplasm.userid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.userid
	 * @param userid  the value for germplasm.userid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((breeder == null) ? 0 : breeder.hashCode());
		result = prime * result + ((femaleparent == null) ? 0 : femaleparent.hashCode());
		result = prime * result + ((germplasmname == null) ? 0 : germplasmname.hashCode());
		result = prime * result + ((germplasmtypeid == null) ? 0 : germplasmtypeid.hashCode());
		result = prime * result + ((gid == null) ? 0 : gid.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((ircross == null) ? 0 : ircross.hashCode());
		result = prime * result + ((irnumber == null) ? 0 : irnumber.hashCode());
		result = prime * result + ((maleparent == null) ? 0 : maleparent.hashCode());
		result = prime * result + ((othername == null) ? 0 : othername.hashCode());
		result = prime * result + ((parentage == null) ? 0 : parentage.hashCode());
		result = prime * result + ((remarks == null) ? 0 : remarks.hashCode());
		result = prime * result + ((selectionhistory == null) ? 0 : selectionhistory.hashCode());
		result = prime * result + ((source == null) ? 0 : source.hashCode());
		result = prime * result + ((userid == null) ? 0 : userid.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */

	@Override
	public String toString() {
		return "Germplasm [id=" + id + ", gid=" + gid + ", germplasmname=" + germplasmname + ", othername=" + othername + ", breeder=" + breeder + ", germplasmtypeid=" + germplasmtypeid + ", irnumber=" + irnumber + ", ircross=" + ircross + ", parentage=" + parentage
				+ ", femaleparent=" + femaleparent + ", maleparent=" + maleparent + ", selectionhistory=" + selectionhistory + ", source=" + source + ", remarks=" + remarks + ", userid=" + userid + "]";
	}
}