package org.strasa.middleware.model;

public class Location {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.locationname
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String locationname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.country
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String country;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.province
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String province;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.region
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String region;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.altitude
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String altitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.latitude
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.weatherstation
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String weatherstation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.userid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer userid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.id
	 * @return  the value of location.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.id
	 * @param id  the value for location.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.locationname
	 * @return  the value of location.locationname
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getLocationname() {
		return locationname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.locationname
	 * @param locationname  the value for location.locationname
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setLocationname(String locationname) {
		this.locationname = locationname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.country
	 * @return  the value of location.country
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.country
	 * @param country  the value for location.country
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.province
	 * @return  the value of location.province
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.province
	 * @param province  the value for location.province
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setProvince(String province) {
		this.province = province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.region
	 * @return  the value of location.region
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getRegion() {
		return region;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.region
	 * @param region  the value for location.region
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setRegion(String region) {
		this.region = region;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.altitude
	 * @return  the value of location.altitude
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getAltitude() {
		return altitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.altitude
	 * @param altitude  the value for location.altitude
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setAltitude(String altitude) {
		this.altitude = altitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.latitude
	 * @return  the value of location.latitude
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.latitude
	 * @param latitude  the value for location.latitude
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.weatherstation
	 * @return  the value of location.weatherstation
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getWeatherstation() {
		return weatherstation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.weatherstation
	 * @param weatherstation  the value for location.weatherstation
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setWeatherstation(String weatherstation) {
		this.weatherstation = weatherstation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.userid
	 * @return  the value of location.userid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.userid
	 * @param userid  the value for location.userid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	@Override
	public String toString() {
		return "Location [id=" + id + ", locationname=" + locationname
				+ ", country=" + country + ", province=" + province
				+ ", region=" + region + ", altitude=" + altitude
				+ ", latitude=" + latitude + ", weatherstation="
				+ weatherstation + "]";
	}
}