package org.strasa.middleware.model;

public class PlantingType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plantingtype.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plantingtype.planting
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String planting;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plantingtype.id
	 * @return  the value of plantingtype.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plantingtype.id
	 * @param id  the value for plantingtype.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plantingtype.planting
	 * @return  the value of plantingtype.planting
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getPlanting() {
		return planting;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plantingtype.planting
	 * @param planting  the value for plantingtype.planting
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setPlanting(String planting) {
		this.planting = planting;
	}
}