package org.strasa.middleware.model;

public class StudyDataColumn {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydatacolumn.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydatacolumn.studyid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer studyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydatacolumn.dataset
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer dataset;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydatacolumn.columnheader
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String columnheader;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydatacolumn.datatype
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String datatype;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydatacolumn.id
	 * @return  the value of studydatacolumn.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydatacolumn.id
	 * @param id  the value for studydatacolumn.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydatacolumn.studyid
	 * @return  the value of studydatacolumn.studyid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getStudyid() {
		return studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydatacolumn.studyid
	 * @param studyid  the value for studydatacolumn.studyid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setStudyid(Integer studyid) {
		this.studyid = studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydatacolumn.dataset
	 * @return  the value of studydatacolumn.dataset
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getDataset() {
		return dataset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydatacolumn.dataset
	 * @param dataset  the value for studydatacolumn.dataset
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setDataset(Integer dataset) {
		this.dataset = dataset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydatacolumn.columnheader
	 * @return  the value of studydatacolumn.columnheader
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getColumnheader() {
		return columnheader;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydatacolumn.columnheader
	 * @param columnheader  the value for studydatacolumn.columnheader
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setColumnheader(String columnheader) {
		this.columnheader = columnheader;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydatacolumn.datatype
	 * @return  the value of studydatacolumn.datatype
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getDatatype() {
		return datatype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydatacolumn.datatype
	 * @param datatype  the value for studydatacolumn.datatype
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setDatatype(String datatype) {
		this.datatype = datatype;
	}
}