package org.strasa.middleware.model;

public class StudyColumnHeader {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studycolumnheader.id
	 * @mbggenerated  Wed Nov 06 13:16:02 SGT 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studycolumnheader.studyid
	 * @mbggenerated  Wed Nov 06 13:16:02 SGT 2013
	 */
	private Integer studyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studycolumnheader.columnheader
	 * @mbggenerated  Wed Nov 06 13:16:02 SGT 2013
	 */
	private String columnheader;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studycolumnheader.id
	 * @return  the value of studycolumnheader.id
	 * @mbggenerated  Wed Nov 06 13:16:02 SGT 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studycolumnheader.id
	 * @param id  the value for studycolumnheader.id
	 * @mbggenerated  Wed Nov 06 13:16:02 SGT 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studycolumnheader.studyid
	 * @return  the value of studycolumnheader.studyid
	 * @mbggenerated  Wed Nov 06 13:16:02 SGT 2013
	 */
	public Integer getStudyid() {
		return studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studycolumnheader.studyid
	 * @param studyid  the value for studycolumnheader.studyid
	 * @mbggenerated  Wed Nov 06 13:16:02 SGT 2013
	 */
	public void setStudyid(Integer studyid) {
		this.studyid = studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studycolumnheader.columnheader
	 * @return  the value of studycolumnheader.columnheader
	 * @mbggenerated  Wed Nov 06 13:16:02 SGT 2013
	 */
	public String getColumnheader() {
		return columnheader;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studycolumnheader.columnheader
	 * @param columnheader  the value for studycolumnheader.columnheader
	 * @mbggenerated  Wed Nov 06 13:16:02 SGT 2013
	 */
	public void setColumnheader(String columnheader) {
		this.columnheader = columnheader;
	}
}