package org.strasa.middleware.model;

import java.util.Date;

public class StudyAgronomy {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyagronomy.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyagronomy.studysiteid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer studysiteid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyagronomy.plantingtypeid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer plantingtypeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyagronomy.sowingdate
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Date sowingdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyagronomy.harvestdate
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Date harvestdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyagronomy.fertilization
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String fertilization;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyagronomy.density
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String density;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyagronomy.id
	 * @return  the value of studyagronomy.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyagronomy.id
	 * @param id  the value for studyagronomy.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyagronomy.studysiteid
	 * @return  the value of studyagronomy.studysiteid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getStudysiteid() {
		return studysiteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyagronomy.studysiteid
	 * @param studysiteid  the value for studyagronomy.studysiteid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setStudysiteid(Integer studysiteid) {
		this.studysiteid = studysiteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyagronomy.plantingtypeid
	 * @return  the value of studyagronomy.plantingtypeid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getPlantingtypeid() {
		return plantingtypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyagronomy.plantingtypeid
	 * @param plantingtypeid  the value for studyagronomy.plantingtypeid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setPlantingtypeid(Integer plantingtypeid) {
		this.plantingtypeid = plantingtypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyagronomy.sowingdate
	 * @return  the value of studyagronomy.sowingdate
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Date getSowingdate() {
		return sowingdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyagronomy.sowingdate
	 * @param sowingdate  the value for studyagronomy.sowingdate
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setSowingdate(Date sowingdate) {
		this.sowingdate = sowingdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyagronomy.harvestdate
	 * @return  the value of studyagronomy.harvestdate
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Date getHarvestdate() {
		return harvestdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyagronomy.harvestdate
	 * @param harvestdate  the value for studyagronomy.harvestdate
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setHarvestdate(Date harvestdate) {
		this.harvestdate = harvestdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyagronomy.fertilization
	 * @return  the value of studyagronomy.fertilization
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getFertilization() {
		return fertilization;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyagronomy.fertilization
	 * @param fertilization  the value for studyagronomy.fertilization
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setFertilization(String fertilization) {
		this.fertilization = fertilization;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyagronomy.density
	 * @return  the value of studyagronomy.density
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getDensity() {
		return density;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyagronomy.density
	 * @param density  the value for studyagronomy.density
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setDensity(String density) {
		this.density = density;
	}

	@Override
	public String toString() {
		return "StudyAgronomy [id=" + id + ", studysiteid=" + studysiteid
				+ ", plantingtypeid=" + plantingtypeid + ", sowingdate="
				+ sowingdate + ", harvestdate=" + harvestdate
				+ ", fertilization=" + fertilization + ", density=" + density
				+ "]";
	}
}