package org.strasa.middleware.model;

import java.util.Date;

public class Study {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study.userid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study.programid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer programid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study.projectid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer projectid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study.name
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study.description
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study.studytypeid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer studytypeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study.startyear
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String startyear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study.endyear
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String endyear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study.remarks
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study.shared
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Boolean shared;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study.datecreated
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Date datecreated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study.datelastmodified
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Date datelastmodified;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study.id
	 * @return  the value of study.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study.id
	 * @param id  the value for study.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study.userid
	 * @return  the value of study.userid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study.userid
	 * @param userid  the value for study.userid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study.programid
	 * @return  the value of study.programid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getProgramid() {
		return programid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study.programid
	 * @param programid  the value for study.programid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setProgramid(Integer programid) {
		this.programid = programid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study.projectid
	 * @return  the value of study.projectid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getProjectid() {
		return projectid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study.projectid
	 * @param projectid  the value for study.projectid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setProjectid(Integer projectid) {
		this.projectid = projectid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study.name
	 * @return  the value of study.name
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study.name
	 * @param name  the value for study.name
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study.description
	 * @return  the value of study.description
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study.description
	 * @param description  the value for study.description
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study.studytypeid
	 * @return  the value of study.studytypeid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getStudytypeid() {
		return studytypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study.studytypeid
	 * @param studytypeid  the value for study.studytypeid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setStudytypeid(Integer studytypeid) {
		this.studytypeid = studytypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study.startyear
	 * @return  the value of study.startyear
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getStartyear() {
		return startyear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study.startyear
	 * @param startyear  the value for study.startyear
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setStartyear(String startyear) {
		this.startyear = startyear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study.endyear
	 * @return  the value of study.endyear
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getEndyear() {
		return endyear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study.endyear
	 * @param endyear  the value for study.endyear
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setEndyear(String endyear) {
		this.endyear = endyear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study.remarks
	 * @return  the value of study.remarks
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study.remarks
	 * @param remarks  the value for study.remarks
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study.shared
	 * @return  the value of study.shared
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Boolean getShared() {
		return shared;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study.shared
	 * @param shared  the value for study.shared
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setShared(Boolean shared) {
		this.shared = shared;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study.datecreated
	 * @return  the value of study.datecreated
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Date getDatecreated() {
		return datecreated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study.datecreated
	 * @param datecreated  the value for study.datecreated
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study.datelastmodified
	 * @return  the value of study.datelastmodified
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Date getDatelastmodified() {
		return datelastmodified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study.datelastmodified
	 * @param datelastmodified  the value for study.datelastmodified
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setDatelastmodified(Date datelastmodified) {
		this.datelastmodified = datelastmodified;
	}
}