package org.strasa.middleware.model;

public class StudyRawDataByDataColumn {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyrawdata.studyid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer studyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyrawdata.dataset
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer dataset;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyrawdata.datacolumn
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String datacolumn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyrawdata.datavalue
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String datavalue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyrawdata.shared
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Boolean shared;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyrawdata.userid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer userid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyrawdata.studyid
	 * @return  the value of studyrawdata.studyid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getStudyid() {
		return studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyrawdata.studyid
	 * @param studyid  the value for studyrawdata.studyid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setStudyid(Integer studyid) {
		this.studyid = studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyrawdata.dataset
	 * @return  the value of studyrawdata.dataset
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getDataset() {
		return dataset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyrawdata.dataset
	 * @param dataset  the value for studyrawdata.dataset
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setDataset(Integer dataset) {
		this.dataset = dataset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyrawdata.datacolumn
	 * @return  the value of studyrawdata.datacolumn
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getDatacolumn() {
		return datacolumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyrawdata.datacolumn
	 * @param datacolumn  the value for studyrawdata.datacolumn
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setDatacolumn(String datacolumn) {
		this.datacolumn = datacolumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyrawdata.datavalue
	 * @return  the value of studyrawdata.datavalue
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getDatavalue() {
		return datavalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyrawdata.datavalue
	 * @param datavalue  the value for studyrawdata.datavalue
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setDatavalue(String datavalue) {
		this.datavalue = datavalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyrawdata.shared
	 * @return  the value of studyrawdata.shared
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Boolean getShared() {
		return shared;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyrawdata.shared
	 * @param shared  the value for studyrawdata.shared
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setShared(Boolean shared) {
		this.shared = shared;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyrawdata.userid
	 * @return  the value of studyrawdata.userid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyrawdata.userid
	 * @param userid  the value for studyrawdata.userid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}
}